<a href="https://colab.research.google.com/github/Rakeen-Harmain/ResoluteAi_Software_Internship/blob/main/Task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=20.5
print(a)
type(a)


20.5


float

In [ ]:
b=4+6j
type(b)

complex

In [ ]:
c=4
print(type(c))
d=complex(a,c)
print(d)

<class 'int'>
(20.5+4j)


In [ ]:
l=[25,65,55,87]
print(l)
print(type(l))

[25, 65, 55, 87]
<class 'list'>


In [ ]:
set={5,6,8,6}
print(set)
print(type(set))

{8, 5, 6}
<class 'set'>


In [ ]:
tuple=(57,87,98)
print(tuple)
print(type(tuple))

(57, 87, 98)
<class 'tuple'>


In [ ]:
z="rakeen"
print(z)

rakeen


In [ ]:
range(10)
list(range(10))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
dic={'rak':'een'}
print(dic.keys())
print(dic.values())
print(dic['rak'])

dict_keys(['rak'])
dict_values(['een'])
een


In [ ]:
a,b=5,6
print(a+b)
a+=5
print(a+b)
b=-b
print(a+b)

11
16
4


In [ ]:
c,d=6,7
print(c==d)
print(c>=d)
print(c<=d)

False
False
True


In [ ]:
print(bin(25))
print(0b101)

0b11001
5


In [ ]:
print(oct(33))
print(hex(50))
print(0xf)
print(hex(11))
print(0b110110)

0o41
0x32
15
0xb
54


In [ ]:
~112

-113

In [ ]:
25|30

31

In [ ]:
25&55

17

In [ ]:
25^55

46

In [ ]:
a=input("enter a")
b=input("enter b")
c=a+b
print(c)

enter a5
enter b5
55


In [ ]:
a=int(input("enter a"))
b=int(input("enter b"))
c=a+b
print(c)

enter a55
enter b54
109


In [ ]:
d=input("enter a char")[0]
print(d)

enter a charrakeen
r


In [ ]:
r=eval(input("expression"))
print(r)

expression5+6+9*2
29


In [ ]:
n=[55,56,87]
n[0:]

[55, 56, 87]

In [ ]:
n[2:]

[87]

In [ ]:
n.append(25)

[55, 56, 87, 25, 25]

In [ ]:
a=['rakeen','harmain','khan']
b=[n,a]
b

[[55, 56, 87, 25, 25], ['rakeen', 'harmain', 'khan']]

In [ ]:
n.insert(2,8)
b

[[55, 56, 8, 87, 25, 25], ['rakeen', 'harmain', 'khan']]

In [ ]:
n.remove(8)
b

[[55, 56, 87, 25, 25], ['rakeen', 'harmain', 'khan']]

In [ ]:
n.pop(3)
b

[[55, 56, 87, 25], ['rakeen', 'harmain', 'khan']]

In [ ]:
n.extend([98,65])
b

[[55, 56, 87, 25, 98, 65], ['rakeen', 'harmain', 'khan']]

In [ ]:
print(max(n))
print(min(n))
print(sum(n))
n.sort()
print(n)

98
25
386
[25, 55, 56, 65, 87, 98]


In [ ]:
d={1:'rakeen',2:'harmain',3:'khan'}
d

{1: 'rakeen', 2: 'harmain', 3: 'khan'}

In [ ]:
keys=[1,2,3]
val=['rakeen','harmain','khan']
dic= dict(zip(keys,val))
dic

{1: 'rakeen', 2: 'harmain', 3: 'khan'}

In [ ]:
del dic[3]
dic

{1: 'rakeen', 2: 'harmain'}

In [ ]:
pr= {'js':'atom','python':['pycharm','spyder'],'java':{'jse':'netbeans','jee':'eclipse'}}
pr

{'js': 'atom',
 'python': ['pycharm', 'spyder'],
 'java': {'jse': 'netbeans', 'jee': 'eclipse'}}

In [ ]:
pr['java']

{'jse': 'netbeans', 'jee': 'eclipse'}

In [ ]:
i,j=1,1
while i<5:
    print("hi ",end="")
    j=1
    while j<4:
        print("there ",end="")
        j+=1
    i+=1
    print("")

hi there there there 
hi there there there 
hi there there there 
hi there there there 


In [ ]:
n=[12,54,21,10,20]
for i in n:
    if i%5==0:
        print(i)
        break
else:
    print("not found")

10


In [ ]:
from array import *
val = array('i',[5,9,6,-6,8])
val.reverse()
print(val)

array('i', [8, -6, 6, 9, 5])


In [ ]:
from array import *
val = array('i',[5,9,6,-6,8])

for i in range(len(val)):
    print(val[i])

5
9
6
-6
8


In [ ]:
from array import *
val = array('i',[5,9,6,-6,8])
new=array(val.typecode, (a*a for a in val))
i=0
while i<len(new):
    print(new[i])
    i+=1

25
81
36
36
64


In [ ]:
from numpy import *
ar=array([12,23,34])
print(ar)

[12 23 34]


In [ ]:
from numpy import *
ar=linspace(0,5)
print(ar)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


In [ ]:
from numpy import *
ar=arange(0,11,2)
print(ar)

[ 0  2  4  6  8 10]


In [ ]:
from numpy import *
ar=logspace(0,11,5)
print(ar)

[1.00000000e+00 5.62341325e+02 3.16227766e+05 1.77827941e+08
 1.00000000e+11]


In [ ]:
from numpy import *
ar1= array([
    [1,2,3,4,5,6],
    [7,8,9,10,11,12]
])
ar2=ar1.flatten()
ar3=ar2.reshape(2,2,3)
print(ar2,"\n")
print(ar3)

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
m=matrix('1 2 3;3 4 4;4 5 6')
print(m)
print(diagonal(m))
print(m.max())

[[1 2 3]
 [3 4 4]
 [4 5 6]]
[1 4 6]
6


In [ ]:
def add(a,b,c):
    c=a+b+c
    return c
result =add(5,8,5)
print(result)

18


In [ ]:
def add(*b):
    c=0
    for i in b:
        c+=i
    return c
result =add(5,8,5)
print(result)

18


In [ ]:
a=10

def fun():
    a=9
    x=globals()['a']
    print(x,a)
    globals()['a']=12
    print(a)
fun()
print(a)

10 9
9
12


In [ ]:
l= lambda a: a*a
result =l(6)
print(result)

36


In [ ]:
num=[1,2,3,4,5,6]
even=list(filter(lambda n: n%2==0,num))
print(even)

[2, 4, 6]


In [ ]:
num=[1,2,3,4,5,6]
even=list(filter(lambda n: n%2==0,num))
double=list(map(lambda n:n*2,even))
print(even)
print(double)

[2, 4, 6]
[4, 8, 12]


In [ ]:
from functools import reduce
num=[1,2,3,4,5,6]
even=list(filter(lambda n: n%2==0,num))
double=list(map(lambda n:n*2,even))
add =reduce(lambda a,b:a+b,double)
print(even)
print(double)
print(add)

[2, 4, 6]
[4, 8, 12]
24


In [ ]:
def div(a,b):
    print(a/b)
    
def div1(func):
    def inside(a,b):
        if a<b:
            a,b=b,a
        return func(a,b)
    return inside
div = div1(div)
div(2,4)

2.0


In [ ]:
class computer:
        def __init__(self):
            self.name='rakeen'
            self.age=20
        
        def compare(self,other):
            if self.age==other.age:
                return True
            else: 
                return False

c1=computer()
c2=computer()

if c1.compare(c2):
    print("same")
else:
    print("different")
    
print(c1.name)
print(c2.name)

same
rakeen
rakeen


In [ ]:
class schl:
    school='pesit'
    
    def __init__(self,m1,m2,m3):
        self.m1=m1
        self.m2=m2
        self.m3=m3
    
    def avg(self):
        return (self.m1+self.m2+self.m3)/3
    
    @classmethod 
    def info(cls):
        return cls.school
    @staticmethod
    def new():
        print("Static")
    
c1=schl(10,20,30)

print(c1.avg())
print(schl.info())
schl.new()

20.0
pesit
Static


In [ ]:
class stud:
    def __init__(self,nm, roll):
        self.nm=nm
        self.roll=roll
        self.lap=self.lappy()
        
    def show(self):
        print(self.nm, self.roll)
        self.lap.show()
        
    class lappy:
        def __init__(self):
            self.brand= 'asus'
            self.ram=16
        
        def show(self):
            print(self.brand, self.ram)    
        
        
        
s1=stud('rakeen', 32)

l1=stud.lappy()

s1.show()
l1.show()

rakeen 32
asus 16
asus 16


In [ ]:
class A:
    def feature1(self):
        print("Feature 1 works")
    
    def feature2(self):
        print("Feature 2 works")

        

class B(A):
    def feature3(self):
        print("Feature 3 works")
    
    def feature4(self):
        print("Feature 4 works")  
        
        
a1=A()

b1=B()

a1.feature1()
a1.feature2()

b1.feature1()
b1.feature2()
b1.feature3()
b1.feature4()

Feature 1 works
Feature 2 works
Feature 1 works
Feature 2 works
Feature 3 works
Feature 4 works


In [ ]:
class A:
    def feature1(self):
        print("Feature 1 works")
    
    def feature2(self):
        print("Feature 2 works")

        

class B:
    def feature3(self):
        print("Feature 3 works")
    
    def feature4(self):
        print("Feature 4 works")  
        
class C(A,B):
    def feature5(self):
        print("Feature 5 works")
        
        
a1=A()

b1=B()
c1=C()
a1.feature1()
a1.feature2()


b1.feature3()
b1.feature4()

c1.feature2()
c1.feature4()
c1.feature5()

Feature 1 works
Feature 2 works
Feature 3 works
Feature 4 works
Feature 2 works
Feature 4 works
Feature 5 works


In [ ]:
class A:
    def __init__(self):
        print("A init")
    
    def feature1(self):
        print("Feature 1 works")
    
    def feature2(self):
        print("Feature 2 works")

        

class B(A):
    def __init__(self):
        super().__init__()
        print("B init")
    
    def feature3(self):
        print("Feature 3 works")
    
    def feature4(self):
        print("Feature 4 works")  
        
        


b1=B()



A init
B init


In [ ]:
class lappy:
  def code(self,ide):
    ide.execute()

class core():
  def execute(self):
    print("compiling")
    print("executing")

class another():
  def execute(self):
    print("compiling (another)")
    print("executing (another)")

ide=core()

l1=lappy()

l1.code(ide)

compiling
executing


In [ ]:
class lappy:
  def code(self,ide):
    ide.execute()

class core():
  def execute(self):
    print("compiling")
    print("executing")

class another():
  def execute(self):
    print("compiling (another)")
    print("executing (another)")

ide=another()

l1=lappy()

l1.code(ide)

compiling (another)
executing (another)


In [ ]:
class stud: 
  def __init__(self,m1,m2):
    self.m1=m1
    self.m2=m2

  def __add__(self,other):
    m1=self.m1+other.m1
    m2=self.m2+other.m2
    s3=stud(m1,m2)
    return s3

s1=stud(55,66)
s2=stud(6,55)

s3= s1 + s2

print(s3.m1)

61


In [ ]:
class stud: 
  def __init__(self,m1,m2):
    self.m1=m1
    self.m2=m2

  def __add__(self,other):
    m1=self.m1+other.m1
    m2=self.m2+other.m2
    s3=stud(m1,m2)
    return s3

  def __str__(self):
    return self.m1,self.m2



s1=stud(55,66)
s2=stud(6,55)
print(s1.__str__())


(55, 66)


In [ ]:
class stud: 
  def __init__(self,m1,m2):
    self.m1=m1
    self.m2=m2

  def sum(self,a=None,b=None,c=None):
    s=0
    if a!=None and b!=None and c!=None:
      s=a+b+c
    elif a!=None and b!=None:
      s=a+b
    else:
      s=a

    return s
   

s1=stud(55,66)
print(s1.sum(55,5,4))

64


In [ ]:
class A:
  def show(self):
    print("A show")

class B(A):
  def show(self):
      print("B show")

a1=B()
a1.show()

B show


In [ ]:
from abc import ABC, abstractmethod

class comp(ABC):
  @abstractmethod
  def process(self):
    pass

class lappy(comp):
  def process(self):
    print("Running")
    

class prog:
  def work(self,c1):
    print("programming")
    c1.process()

c=lappy()
p=prog()
p.work(c)
#c.process()
c.process()

programming
Running
Running


In [ ]:
a=int(input("A: "))
b=int(input("B: "))
try: 
  print("Entered Try")
  print(a/b)
  print("Operation performed")
  k=int(input("k:"))
  print(k)
except Exception as e:
  print("Cannot divide by 0",e)

A: 5
B: 2
Entered Try
2.5
Operation performed
k:p
Cannot divide by 0 invalid literal for int() with base 10: 'p'


In [ ]:
a=int(input("A: "))
b=int(input("B: "))
try: 
  print("Entered Try")
  print(a/b)
  print("Operation performed")
  k=int(input("k:"))
  print(k)
except ZeroDivisionError as e:
  print("Cannot divide by 0",e)
except ValueError as e:
  print("Invalid Input", e)
finally:
  print("Done")

A: 5
B: 5
Entered Try
1.0
Operation performed
k:q
Invalid Input invalid literal for int() with base 10: 'q'
Done


In [ ]:
from time import sleep
from threading import *

class USA(Thread):
  def run(self):
    for i in range(5):
      print("America ")
      sleep(1)

class UK(Thread):
  def run(self):
    for i in range(5):
      print("British")
      sleep(1)

t1=USA()
t2=UK()
t1.start()
sleep(0.2)
t2.start()
t1.join()
t2.join()

America 
British
America 
British
America 
British
America 
British
America 
British


In [ ]:
file = '/content/drive/MyDrive/Notepad.txt'

with open(file, 'w') as file:
    file.write("Everyone is a villain in a poorly told story.")


In [ ]:
file = '/content/drive/MyDrive/Notepad.txt'

with open(file, 'r') as file:
    content = file.read()
    print(content)

Everyone is a villain in a poorly told story.
